// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	killSidecar: () => __TAURI_INVOKE<void>("kill_sidecar"),
	installCli: () => __TAURI_INVOKE<string>("install_cli"),
	awaitInitialization: (events: Channel) => __TAURI_INVOKE<ServerReadyData>("await_initialization", { events }),
	workbenchOpenWorkspace: (workspacePath: string) => __TAURI_INVOKE<WorkbenchWorkspace>("workbench_open_workspace", { workspacePath }),
	workbenchIssueToken: (workspaceId: string, capabilities: string[]) => __TAURI_INVOKE<WorkbenchLease>("workbench_issue_token", { workspaceId, capabilities }),
	workbenchRotateToken: (workspaceId: string, capabilities: string[]) => __TAURI_INVOKE<WorkbenchRotation>("workbench_rotate_token", { workspaceId, capabilities }),
	workbenchRevokeToken: (workspaceId: string) => __TAURI_INVOKE<null>("workbench_revoke_token", { workspaceId }),
	getDefaultServerUrl: () => __TAURI_INVOKE<string | null>("get_default_server_url"),
	setDefaultServerUrl: (url: string | null) => __TAURI_INVOKE<null>("set_default_server_url", { url }),
	getWslConfig: () => __TAURI_INVOKE<WslConfig>("get_wsl_config"),
	setWslConfig: (config: WslConfig) => __TAURI_INVOKE<null>("set_wsl_config", { config }),
	getRemoteConfig: () => __TAURI_INVOKE<RemoteConnectionInfo>("get_remote_config"),
	setRemoteEnabled: (enabled: boolean) => __TAURI_INVOKE<RemoteConnectionInfo>("set_remote_enabled", { enabled }),
	resetRemotePassword: () => __TAURI_INVOKE<RemoteConnectionInfo>("reset_remote_password"),
	setRemoteCredentials: (username: string, password: string) => __TAURI_INVOKE<RemoteConnectionInfo>("set_remote_credentials", { username, password }),
	setInternetMode: (enabled: boolean) => __TAURI_INVOKE<RemoteConnectionInfo>("set_internet_mode", { enabled }),
	exportTlsCert: () => __TAURI_INVOKE<string>("export_tls_cert"),
	rotateTlsCert: () => __TAURI_INVOKE<RemoteConnectionInfo>("rotate_tls_cert"),
	getDisplayBackend: () => __TAURI_INVOKE<"wayland" | "auto" | null>("get_display_backend"),
	setDisplayBackend: (backend: LinuxDisplayBackend) => __TAURI_INVOKE<null>("set_display_backend", { backend }),
	getThermalState: () => __TAURI_INVOKE<string>("get_thermal_state"),
	parseMarkdownCommand: (markdown: string) => __TAURI_INVOKE<string>("parse_markdown_command", { markdown }),
	checkAppExists: (appName: string) => __TAURI_INVOKE<boolean>("check_app_exists", { appName }),
	wslPath: (path: string, mode: "windows" | "linux" | null) => __TAURI_INVOKE<string>("wsl_path", { path, mode }),
	resolveAppPath: (appName: string) => __TAURI_INVOKE<string | null>("resolve_app_path", { appName }),
	openPath: (path: string, appName: string | null) => __TAURI_INVOKE<null>("open_path", { path, appName }),
	listModels: () => __TAURI_INVOKE<ModelInfo[]>("list_models"),
	downloadModel: (url: string, filename: string) => __TAURI_INVOKE<null>("download_model", { url, filename }),
	deleteModel: (filename: string) => __TAURI_INVOKE<null>("delete_model", { filename }),
	checkLlmHealth: (port: number | null) => __TAURI_INVOKE<boolean>("check_llm_health", { port }),
	loadLlmModel: (filename: string, draftModel: string | null) => __TAURI_INVOKE<null>("load_llm_model", { filename, draftModel }),
	unloadLlmModel: () => __TAURI_INVOKE<null>("unload_llm_model"),
	getVramInfo: () => __TAURI_INVOKE<VramInfo>("get_vram_info"),
	setLlmConfig: (args: SetLlmConfigArgs) => __TAURI_INVOKE<null>("set_llm_config", { args }),
	detectActiveBackend: () => __TAURI_INVOKE<string>("detect_active_backend"),
	runInferenceBenchmark: (prompt: string, nPredict: number) => __TAURI_INVOKE<BenchmarkResult>("run_inference_benchmark", { prompt, nPredict }),
	ttsStart: () => __TAURI_INVOKE<number>("tts_start"),
	ttsSpeak: (text: string, voice: string | null) => __TAURI_INVOKE<string>("tts_speak", { text, voice }),
	ttsStop: () => __TAURI_INVOKE<null>("tts_stop"),
	ttsSaveVoiceClone: (audioBase64: string, name: string) => __TAURI_INVOKE<string>("tts_save_voice_clone", { audioBase64, name }),
	ttsListVoiceClones: () => __TAURI_INVOKE<string[]>("tts_list_voice_clones"),
	ttsDeleteVoiceClone: (name: string) => __TAURI_INVOKE<null>("tts_delete_voice_clone", { name }),
	ttsAvailable: () => __TAURI_INVOKE<boolean>("tts_available"),
	ttsCleanupChunks: () => __TAURI_INVOKE<null>("tts_cleanup_chunks"),
	sttDownloadModel: () => __TAURI_INVOKE<null>("stt_download_model"),
	sttLoadModel: () => __TAURI_INVOKE<null>("stt_load_model"),
	sttTranscribe: (audioBase64: string) => __TAURI_INVOKE<string>("stt_transcribe", { audioBase64 }),
	sttAvailable: () => __TAURI_INVOKE<boolean>("stt_available"),
	sttLoaded: () => __TAURI_INVOKE<boolean>("stt_loaded"),
	kokoroAvailable: () => __TAURI_INVOKE<boolean>("kokoro_available"),
	kokoroDownloadModel: () => __TAURI_INVOKE<null>("kokoro_download_model"),
	kokoroLoad: () => __TAURI_INVOKE<null>("kokoro_load"),
	kokoroLoaded: () => __TAURI_INVOKE<boolean>("kokoro_loaded"),
	kokoroVoices: () => __TAURI_INVOKE<string[]>("kokoro_voices"),
	kokoroSynthesize: (text: string, voice: string, speed: number) => __TAURI_INVOKE<string>("kokoro_synthesize", { text, voice, speed }),
	authStorageGet: (service: string, key: string) => __TAURI_INVOKE<string | null>("auth_storage_get", { service, key }),
	authStorageSet: (service: string, key: string, value: string) => __TAURI_INVOKE<null>("auth_storage_set", { service, key, value }),
	authStorageDelete: (service: string, key: string) => __TAURI_INVOKE<null>("auth_storage_delete", { service, key }),
	authStorageList: (service: string) => __TAURI_INVOKE<string[]>("auth_storage_list", { service }),
};

/** Events */
export const events = {
	loadingWindowComplete: makeEvent<LoadingWindowComplete>("loading-window-complete"),
	sqliteMigrationProgress: makeEvent<SqliteMigrationProgress>("sqlite-migration-progress"),
};

/* Types */
export type BenchmarkResult = {
		prompt_tokens: number,
		generated_tokens: number,
		prefill_ms: number,
		decode_ms: number,
		prefill_tps: number,
		decode_tps: number,
		peak_ram_mib: number | null,
		device_label: string | null,
	};

export type InitStep = { phase: "server_waiting" } | { phase: "sqlite_waiting" } | { phase: "done" };

export type LinuxDisplayBackend = "wayland" | "auto";

export type LoadingWindowComplete = null;

export type ModelInfo = {
		filename: string,
		size: number,
	};

/**
 * Information the frontend needs to display connection instructions for
 * a paired client (QR code, banner, etc.).
 */
export type RemoteConnectionInfo = {
		enabled: boolean,
		password: string,
		username: string,
		port: number,
		
	/**
 * Best-effort detected LAN address. None if no non-loopback interface is
 * reachable (offline, all interfaces down, etc.).
 */
lanIp: string | null,
		
	/**
 * Whether TLS (Internet mode) is active.
 */
tlsEnabled: boolean,
		
	/**
 * SHA-256 fingerprint of the self-signed cert (colon-separated hex).
 * Only present when tls_enabled is true.
 */
tlsFingerprint: string | null,
	};

export type ServerReadyData = {
		url: string,
		username: string | null,
		password: string | null,
	};

/**
 * Set LLM configuration env vars (called by frontend before load).
 * Mirror of mobile's set_llm_config: every field is optional, env vars
 * are read by load_llm_model() on the next start, and (for top_k/top_p/
 * temperature/system_prompt) by the agent-side request builder.
 * Maps to existing desktop env names where they exist (OPENCODE_N_THREADS,
 * OPENCODE_BATCH_SIZE) so the Rust spawn path keeps using its current vars.
 * 
 * Args are bundled in a struct because specta_fn caps at fewer positional
 * parameters; this also gives a stable JS contract for `invoke("set_llm_config", { ... })`.
 */
export type SetLlmConfigArgs = {
		kvCacheType: string | null,
		flashAttn: boolean | null,
		offloadMode: string | null,
		mmapMode: string | null,
		accelerator: string | null,
		threads: number | null,
		nBatch: number | null,
		cacheReuse: boolean | null,
		topK: number | null,
		topP: number | null,
		temperature: number | null,
		systemPrompt: string | null,
	};

export type SqliteMigrationProgress = { type: "InProgress"; value: number } | { type: "Done" };

/**
 * Get GPU VRAM info (total, used, free) in MiB
 */
export type VramInfo = {
		total_mib: number,
		used_mib: number,
		free_mib: number,
		gpu_name: string,
	};

export type WorkbenchLease = {
		token: string,
		tokenId: string,
		instanceId: string,
		workspaceId: string,
		capabilities: string[],
		issuedAt: number,
		expiresAt: number,
	};

export type WorkbenchRotation = {
		token: WorkbenchLease,
		previousToken: string | null,
		gracePeriodMs: number,
	};

export type WorkbenchWorkspace = {
		workspaceId: string,
		instanceId: string,
	};

export type WslConfig = {
		enabled: boolean,
	};

export type WslPathMode = "windows" | "linux";

/* Tauri Specta runtime */
function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: (payload: T) => __TAURI_EVENT.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: (payload: T) => target.emit(name, payload) as unknown as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

