#!/usr/bin/env bun
/**
 * Génère THIRD_PARTY_NOTICES.md depuis un registry model-intelligence.
 *
 * Usage :
 *   bun run script/build-notices.ts [--registry <path-to-registry.json>]
 *
 * Sortie :
 *   - THIRD_PARTY_NOTICES.md à la racine du dépôt opencode/
 *
 * CI : ce script DOIT être exécuté avant chaque commit modifiant le
 * snapshot ; le diff doit être vide (cf. .github/workflows/ci-model-intelligence.yml).
 */

import * as fs from "node:fs/promises"
import * as path from "node:path"

const DEFAULT_REGISTRY_PATH = "model-intelligence-snapshot.json"
const OUTPUT_PATH = "THIRD_PARTY_NOTICES.md"

interface NoticeEntry {
  sourceID: string
  licenseCode: string | null
  copyrightNotice: string | null
  licenseFileURL: string | null
  confidenceLevel: string
  url: string
}

interface Registry {
  sources: Array<{
    id: string
    url: string
    licenseCode: string | null
    licenseFileURL: string | null
    copyrightNotice: string | null
    confidenceLevel: string
  }>
}

function buildNotices(sources: Registry["sources"]): NoticeEntry[] {
  return [...sources]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((s) => ({
      sourceID: s.id,
      licenseCode: s.licenseCode,
      copyrightNotice: s.copyrightNotice,
      licenseFileURL: s.licenseFileURL,
      confidenceLevel: s.confidenceLevel,
      url: s.url,
    }))
}

function renderNotices(notices: NoticeEntry[]): string {
  const lines: string[] = []
  lines.push("# THIRD_PARTY_NOTICES")
  lines.push("")
  lines.push(`Generated by \`script/build-notices.ts\` at ${new Date().toISOString()}`)
  lines.push("")
  lines.push("This file is auto-generated from the model-intelligence registry snapshot.")
  lines.push("Do not edit manually. Regenerate via `bun run build-notices`.")
  lines.push("")
  lines.push("Source registry snapshot is bundled with this release.")
  lines.push("")

  const grouped = new Map<string, NoticeEntry[]>()
  for (const n of notices) {
    const key = n.licenseCode ?? "UNKNOWN"
    if (!grouped.has(key)) grouped.set(key, [])
    grouped.get(key)!.push(n)
  }

  const licenseKeys = [...grouped.keys()].sort()
  for (const lic of licenseKeys) {
    lines.push(`## ${lic}`)
    lines.push("")
    for (const n of grouped.get(lic)!) {
      lines.push(`### ${n.sourceID}`)
      lines.push("")
      lines.push(`- License: ${n.licenseCode ?? "(none declared)"}`)
      lines.push(`- Copyright: ${n.copyrightNotice ?? "(none declared)"}`)
      if (n.licenseFileURL) lines.push(`- License file: ${n.licenseFileURL}`)
      lines.push(`- Confidence: ${n.confidenceLevel}`)
      if (n.url) lines.push(`- URL: ${n.url}`)
      lines.push("")
    }
  }

  lines.push("---")
  lines.push("")
  lines.push("## Verification")
  lines.push("")
  lines.push("```bash")
  lines.push("bun run build-notices && git diff --exit-code THIRD_PARTY_NOTICES.md")
  lines.push("```")
  lines.push("")

  return lines.join("\n")
}

async function main() {
  const args = process.argv.slice(2)
  let registryPath = DEFAULT_REGISTRY_PATH
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--registry" && args[i + 1]) {
      registryPath = args[i + 1]!
      i++
    }
  }

  let registry: Registry
  try {
    const content = await fs.readFile(registryPath, "utf-8")
    registry = JSON.parse(content)
  } catch (e) {
    console.error(`Failed to read registry from ${registryPath}:`, e)
    process.exit(1)
  }

  const notices = buildNotices(registry.sources)
  const markdown = renderNotices(notices)
  await fs.writeFile(OUTPUT_PATH, markdown, "utf-8")
  console.log(`Generated ${OUTPUT_PATH} from ${registryPath} (${notices.length} notices)`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})