/* SPDX-License-Identifier: MIT */
//! Mutation WAL (P2.3).
//!
//! Per runbook §13 P2.3 and ADR-KNOW-0004: every mutation of
//! Class A or Class B is preceded by an append to a write-ahead
//! log (WAL). The WAL holds a delta (not the full Markdown),
//! with a previous hash, a new hash, and a scope.
//!
//! Invariants:
//! - The WAL never holds the full Markdown body, only a
//!   reference (path or content-hash-pointer) and the metadata.
//! - On crash before fsync, the previous file is still readable
//!   and the WAL allows idempotent recovery.
//! - On crash after fsync but before rename, the previous file
//!   is still readable.
//! - On crash after rename but before WAL fsync, the new file
//!   is readable; the WAL replay either re-affirms or rolls back.
//! - On crash after WAL fsync, the new file is the source of
//!   truth and the WAL is the audit trail.
//!
//! V1: pure data structures + a tiny append-and-rotate helper.
//! The fsync/atomic-rename pair is in `atomic_write.rs` and is
//! platform-tested in P0.3.

use serde::{Deserialize, Serialize};

use crate::error::KnowledgeError;
use crate::hash::ContentHash;

/// Kind of a WAL entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum WalKind {
    /// Create a new note.
    Create,
    /// Update an existing note.
    Update,
    /// Delete a note.
    Delete,
    /// Move a note.
    Move,
    /// Promote a candidate to active.
    Promote,
    /// Supersede a note.
    Supersede,
    /// Archive a note.
    Archive,
    /// Restore from archive.
    Restore,
}

/// A single WAL entry. Holds the previous and new content hashes
/// plus the locator and the audit id. Body is referenced, not
/// embedded.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WalEntry {
    /// Monotonic sequence, generated by the writer.
    pub seq: u64,
    /// Kind of mutation.
    pub kind: WalKind,
    /// Target locator (relative to the Knowledge Root).
    pub locator: String,
    /// Observed content hash before the mutation. `None` on Create.
    pub previous_hash: Option<ContentHash>,
    /// Content hash after the mutation. `None` on Delete.
    pub new_hash: Option<ContentHash>,
    /// Audit identifier (free-form; usually a ULID/UUIDv7).
    pub audit_id: String,
    /// Source (user or agent).
    pub source: String,
    /// Reason (free-form).
    pub reason: String,
    /// Wall-clock timestamp (ISO-8601 UTC).
    pub timestamp: String,
}

impl WalEntry {
    /// True if this entry is a *terminal* entry (no follow-up
    /// expected).
    pub fn is_terminal(&self) -> bool {
        matches!(self.kind, WalKind::Delete | WalKind::Archive)
    }
}

/// A WAL is an ordered, append-only sequence of entries. The
/// sequence number is monotone and assigned at append time.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Wal {
    entries: Vec<WalEntry>,
    next_seq: u64,
}

impl Wal {
    /// New, empty WAL.
    pub fn new() -> Self {
        Self::default()
    }

    /// Append an entry. Assigns the sequence number.
    pub fn append(
        &mut self,
        kind: WalKind,
        locator: String,
        previous_hash: Option<ContentHash>,
        new_hash: Option<ContentHash>,
        audit_id: String,
        source: String,
        reason: String,
        timestamp: String,
    ) -> Result<&WalEntry, KnowledgeError> {
        if locator.is_empty() {
            return Err(KnowledgeError::mutation_refused(
                "locator must be non-empty",
            ));
        }
        if source.is_empty() {
            return Err(KnowledgeError::mutation_refused("source must be non-empty"));
        }
        if reason.is_empty() {
            return Err(KnowledgeError::mutation_refused("reason must be non-empty"));
        }
        if matches!(kind, WalKind::Create) && previous_hash.is_some() {
            return Err(KnowledgeError::mutation_refused(
                "create must have no previous hash",
            ));
        }
        // Only a physical delete leaves no new content. Archive rewrites the
        // note's lifecycle and keeps the file (ADR-KNOW-0009 §4), so it has a
        // new hash like any other update; grouping the two here made archive
        // impossible to record and therefore impossible to perform.
        if matches!(kind, WalKind::Delete) && new_hash.is_some() {
            return Err(KnowledgeError::mutation_refused(
                "delete must have no new hash",
            ));
        }
        if matches!(kind, WalKind::Archive) && new_hash.is_none() {
            return Err(KnowledgeError::mutation_refused(
                "archive must have a new hash: it rewrites the note",
            ));
        }
        let entry = WalEntry {
            seq: self.next_seq,
            kind,
            locator,
            previous_hash,
            new_hash,
            audit_id,
            source,
            reason,
            timestamp,
        };
        self.next_seq = self
            .next_seq
            .checked_add(1)
            .ok_or_else(|| KnowledgeError::invariant_violated("WAL sequence overflow"))?;
        self.entries.push(entry);
        Ok(self.entries.last().expect("just pushed"))
    }

    /// Borrow entries in order.
    pub fn entries(&self) -> &[WalEntry] {
        &self.entries
    }

    /// True if empty.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Number of entries.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Last entry's sequence number (or 0 if empty).
    pub fn last_seq(&self) -> u64 {
        self.entries.last().map(|e| e.seq).unwrap_or(0)
    }
}

/// A WAL replay plan: the recovery procedure derives this from a
/// WAL and uses it to apply or skip each entry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ReplayPlan {
    pub to_apply: Vec<WalEntry>,
    pub to_skip: Vec<WalEntry>,
}

impl ReplayPlan {
    pub fn is_clean(&self) -> bool {
        self.to_skip.is_empty()
    }
}

/// Compute a replay plan from a WAL. An entry is `to_skip` if it
/// would be applied redundantly (same `audit_id` already seen).
pub fn plan_replay(wal: &Wal) -> ReplayPlan {
    let mut seen_audits = std::collections::HashSet::new();
    let mut to_apply = Vec::with_capacity(wal.entries.len());
    let mut to_skip = Vec::new();
    for e in wal.entries() {
        if seen_audits.insert(e.audit_id.clone()) {
            to_apply.push(e.clone());
        } else {
            to_skip.push(e.clone());
        }
    }
    ReplayPlan { to_apply, to_skip }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_hash(c: char) -> ContentHash {
        // 'a' is a valid hex digit; 'x' is not.
        let ch = if c.is_ascii_hexdigit() { c } else { 'a' };
        ContentHash::from_hex(&ch.to_string().repeat(64)).unwrap()
    }

    #[test]
    fn empty_wal_is_empty() {
        let w = Wal::new();
        assert!(w.is_empty());
        assert_eq!(w.len(), 0);
        assert_eq!(w.last_seq(), 0);
    }

    #[test]
    fn append_increments_sequence() {
        let mut w = Wal::new();
        let _ = w.append(
            WalKind::Create,
            "a.md".to_string(),
            None,
            Some(make_hash('a')),
            "audit-1".into(),
            "test".into(),
            "r".into(),
            "2026-08-29T00:00:00Z".into(),
        );
        let _ = w.append(
            WalKind::Update,
            "a.md".to_string(),
            Some(make_hash('a')),
            Some(make_hash('b')),
            "audit-2".into(),
            "test".into(),
            "r".into(),
            "2026-08-29T00:00:01Z".into(),
        );
        assert_eq!(w.len(), 2);
        assert_eq!(w.last_seq(), 1);
    }

    #[test]
    fn create_rejects_previous_hash() {
        let mut w = Wal::new();
        let r = w.append(
            WalKind::Create,
            "a.md".to_string(),
            Some(make_hash('x')),
            Some(make_hash('a')),
            "audit-1".into(),
            "test".into(),
            "r".into(),
            "2026-08-29T00:00:00Z".into(),
        );
        assert!(r.is_err());
    }

    #[test]
    fn delete_rejects_new_hash() {
        let mut w = Wal::new();
        let r = w.append(
            WalKind::Delete,
            "a.md".to_string(),
            Some(make_hash('a')),
            Some(make_hash('b')),
            "audit-1".into(),
            "test".into(),
            "r".into(),
            "2026-08-29T00:00:00Z".into(),
        );
        assert!(r.is_err());
    }

    #[test]
    fn archive_requires_a_new_hash() {
        // Archive rewrites the note and keeps the file, so it carries a new
        // hash. It used to be grouped with delete and rejected here, which
        // made archiving impossible to record and therefore to perform.
        let mut w = Wal::new();
        let ok = w.append(
            WalKind::Archive,
            "a.md".to_string(),
            Some(make_hash('a')),
            Some(make_hash('b')),
            "audit-1".into(),
            "test".into(),
            "r".into(),
            "2026-08-29T00:00:00Z".into(),
        );
        assert!(ok.is_ok(), "archive with a new hash must be accepted");

        let missing = w.append(
            WalKind::Archive,
            "a.md".to_string(),
            Some(make_hash('a')),
            None,
            "audit-2".into(),
            "test".into(),
            "r".into(),
            "2026-08-29T00:00:00Z".into(),
        );
        assert!(
            missing.is_err(),
            "archive without a new hash must be refused"
        );
    }

    #[test]
    fn plan_replay_deduplicates_by_audit_id() {
        let mut w = Wal::new();
        let _ = w.append(
            WalKind::Create,
            "a.md".into(),
            None,
            Some(make_hash('a')),
            "audit-1".into(),
            "s".into(),
            "r".into(),
            "t".into(),
        );
        let _ = w.append(
            WalKind::Update,
            "a.md".into(),
            Some(make_hash('a')),
            Some(make_hash('b')),
            "audit-1".into(),
            "s".into(),
            "r".into(),
            "t".into(),
        );
        let _ = w.append(
            WalKind::Update,
            "a.md".into(),
            Some(make_hash('b')),
            Some(make_hash('c')),
            "audit-2".into(),
            "s".into(),
            "r".into(),
            "t".into(),
        );
        let p = plan_replay(&w);
        assert_eq!(p.to_apply.len(), 2);
        assert_eq!(p.to_skip.len(), 1);
        assert!(!p.is_clean());
    }
}
