/* SPDX-License-Identifier: MIT */
/**
 * Workspace report (P11.23).
 *
 * Generates a Markdown report of the workspace state. The
 * report is operator-facing: it summarises the summary,
 * the validation findings, the reachability, and the
 * sovereignt-y/verify verdict in a single document that can
 * be pasted into a PR, an issue, or a status update.
 *
 * The report is a pure function of the workspace. It does not
 * mutate state and does not require a network call.
 */

import { summarise, type Summary } from "./summary.js"
import { validate, type ValidationResult } from "./validate.js"
import { isAbsolute } from "node:path"

export interface ReportOptions {
  /** Include the validation findings section (default true). */
  includeValidation?: boolean
  /** Include the type breakdown section (default true). */
  includeTypeBreakdown?: boolean
  /** Include the policy section (default true). */
  includePolicy?: boolean
  /** Optional title for the report header. */
  title?: string
}

export interface ReportInput {
  vaultRoot: string
  options?: ReportOptions
}

export function generateReport(input: ReportInput): string {
  if (!isAbsolute(input.vaultRoot)) {
    throw new Error(`vaultRoot must be absolute, got ${input.vaultRoot}`)
  }
  const opts = input.options ?? {}
  const includeValidation = opts.includeValidation ?? true
  const includeTypeBreakdown = opts.includeTypeBreakdown ?? true
  const includePolicy = opts.includePolicy ?? true
  const title = opts.title ?? "Knowledge Workspace Report"

  const summary: Summary = summarise({ vaultRoot: input.vaultRoot })
  const validation: ValidationResult | null = includeValidation
    ? validate({ vaultRoot: input.vaultRoot })
    : null

  const lines: string[] = []
  lines.push(`# ${title}`)
  lines.push("")
  lines.push(`Generated: ${new Date().toISOString()}`)
  lines.push(`Vault: \`${summary.vaultRoot}\``)
  lines.push("")

  lines.push("## Summary")
  lines.push("")
  lines.push(`- Total notes: ${summary.totalNotes}`)
  lines.push(`- Parse failures: ${summary.parseFailures}`)
  lines.push(`- Class B entries: ${summary.portableStoreEntries}`)
  lines.push(`- Policy egress: ${summary.policyEgress}`)
  lines.push("")

  lines.push("### Lifecycle breakdown")
  lines.push("")
  for (const [k, v] of Object.entries(summary.byLifecycle)) {
    lines.push(`- ${k}: ${v}`)
  }
  lines.push("")

  if (includeTypeBreakdown) {
    lines.push("### Type breakdown")
    lines.push("")
    for (const [k, v] of Object.entries(summary.byType)) {
      lines.push(`- ${k}: ${v}`)
    }
    lines.push("")
  }

  if (includePolicy && summary.policyFeatures) {
    lines.push("## Policy features")
    lines.push("")
    lines.push(`- embedding: ${summary.policyFeatures.embedding}`)
    lines.push(`- mcpServer: ${summary.policyFeatures.mcpServer}`)
    lines.push(`- gitAutoPush: ${summary.policyFeatures.gitAutoPush}`)
    lines.push("")
  }

  if (validation) {
    lines.push("## Validation")
    lines.push("")
    lines.push(`- Notes parsed: ${validation.notesParsed}`)
    lines.push(`- Notes failed: ${validation.notesFailed}`)
    lines.push(`- Findings: ${validation.findings.length}`)
    if (Object.keys(validation.byCategory).length > 0) {
      lines.push("")
      lines.push("### By category")
      lines.push("")
      for (const [k, v] of Object.entries(validation.byCategory)) {
        lines.push(`- ${k}: ${v}`)
      }
    }
    if (validation.findings.length > 0) {
      lines.push("")
      lines.push("### Findings")
      lines.push("")
      for (const f of validation.findings.slice(0, 50)) {
        lines.push(`- [${f.category}] ${f.message}`)
      }
      if (validation.findings.length > 50) {
        lines.push(`- ... and ${validation.findings.length - 50} more`)
      }
    }
    lines.push("")
  }

  lines.push(`---`)
  lines.push("")
  lines.push(`Report generated by unifia-knowledge CLI. Elapsed: ${summary.totalMs}ms.`)
  lines.push("")
  return lines.join("\n")
}
