/* SPDX-License-Identifier: MIT */
/** Turn assistant Markdown into text that is safe and pleasant to speak.
 *
 * TypeScript port of the Python reference in
 * `packages/voice-host/voice_host/live/renderer.py`. Speech is a disclosure
 * channel: anything spoken can be overheard or recorded. The renderer
 * therefore removes secrets outright and reduces content that is unreadable
 * aloud (code, JSON, diffs, stack traces, hashes, long URLs) to a short
 * spoken reference to the conversation, where the full text remains.
 *
 * Parity with the reference implementation is enforced by
 * `packages/voice-core/fixtures/speech-text-parity.json` (generated by
 * `scripts/voice/generate-speech-fixtures.py`, asserted from both the TS and
 * Python suites).
 */
import type { SpeechLanguage } from "@unifia/contracts/speech"
import type { SpeechSegment } from "./speech-segmenter"

export type PhraseKey =
  | "code"
  | "table"
  | "list_rest"
  | "link"
  | "secret"
  | "details"
  | "working"
  | "still_working"
  | "permission"
  | "question"
  | "error"

type PhraseTable = Record<PhraseKey, string>

export const PHRASES: Record<SpeechLanguage, PhraseTable> = {
  en: {
    code: "The code is shown in the conversation.",
    table: "The table is shown in the conversation.",
    list_rest: "There are {count} more items in the conversation.",
    link: "a link",
    secret: "a hidden value",
    details: "The details are in the conversation.",
    working: "Okay, I'm on it.",
    still_working: "Still working on it.",
    permission: "I need your permission to continue. Please check the conversation.",
    question: "I have a question for you in the conversation.",
    error: "Something went wrong. The details are in the conversation.",
  },
  fr: {
    code: "Le code est affiché dans la conversation.",
    table: "Le tableau est affiché dans la conversation.",
    list_rest: "Il y a {count} autres éléments dans la conversation.",
    link: "un lien",
    secret: "une valeur masquée",
    details: "Les détails sont dans la conversation.",
    working: "D'accord, je m'en occupe.",
    still_working: "Je travaille toujours dessus.",
    permission: "J'ai besoin de votre autorisation pour continuer. Regardez la conversation.",
    question: "J'ai une question pour vous dans la conversation.",
    error: "Un problème est survenu. Les détails sont dans la conversation.",
  },
  es: {
    code: "El código se muestra en la conversación.",
    table: "La tabla se muestra en la conversación.",
    list_rest: "Hay {count} elementos más en la conversación.",
    link: "un enlace",
    secret: "un valor oculto",
    details: "Los detalles están en la conversación.",
    working: "De acuerdo, me pongo con ello.",
    still_working: "Sigo trabajando en ello.",
    permission: "Necesito tu permiso para continuar. Revisa la conversación.",
    question: "Tengo una pregunta para ti en la conversación.",
    error: "Algo salió mal. Los detalles están en la conversación.",
  },
  it: {
    code: "Il codice è mostrato nella conversazione.",
    table: "La tabella è mostrata nella conversazione.",
    list_rest: "Ci sono altri {count} elementi nella conversazione.",
    link: "un link",
    secret: "un valore nascosto",
    details: "I dettagli sono nella conversazione.",
    working: "Va bene, me ne occupo.",
    still_working: "Ci sto ancora lavorando.",
    permission: "Ho bisogno del tuo permesso per continuare. Controlla la conversazione.",
    question: "Ho una domanda per te nella conversazione.",
    error: "Qualcosa è andato storto. I dettagli sono nella conversazione.",
  },
  de: {
    code: "Der Code wird im Gespräch angezeigt.",
    table: "Die Tabelle wird im Gespräch angezeigt.",
    list_rest: "Es gibt {count} weitere Punkte im Gespräch.",
    link: "ein Link",
    secret: "ein verborgener Wert",
    details: "Die Details stehen im Gespräch.",
    working: "Okay, ich kümmere mich darum.",
    still_working: "Ich arbeite noch daran.",
    permission: "Ich brauche deine Erlaubnis, um fortzufahren. Bitte sieh im Gespräch nach.",
    question: "Ich habe eine Frage an dich im Gespräch.",
    error: "Etwas ist schiefgelaufen. Die Details stehen im Gespräch.",
  },
}

/** Localised phrase lookup; unknown languages fall back to English (the
 * Python reference does `PHRASES.get(language) or PHRASES["en"]`). */
export function phrase(language: string, key: PhraseKey, values: Record<string, string | number> = {}): string {
  const table = PHRASES[language as SpeechLanguage] ?? PHRASES.en
  return table[key].replace(/\{(\w+)\}/g, (whole, name: string) => String(values[name] ?? whole))
}

/** Secrets are matched before anything else so no later rule can leak them. */
const SECRET_PATTERNS: readonly RegExp[] = [
  /-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?(-----END [A-Z ]*PRIVATE KEY-----|$)/g,
  /\b(?:sk|pk|rk)-[A-Za-z0-9_-]{16,}\b/g,
  /\bsk-ant-[A-Za-z0-9_-]{16,}\b/g,
  /\bgh[pousr]_[A-Za-z0-9]{20,}\b/g,
  /\bgithub_pat_[A-Za-z0-9_]{20,}\b/g,
  /\bxox[abprs]-[A-Za-z0-9-]{10,}\b/g,
  /\bAKIA[0-9A-Z]{16}\b/g,
  /\bAIza[0-9A-Za-z_-]{30,}\b/g,
  /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g,
  /\bbearer\s+[A-Za-z0-9._~+/-]{12,}=*/gi,
  /\b(?:password|passwd|pwd|secret|token|api[_-]?key|access[_-]?key|private[_-]?key|client[_-]?secret)\s*[:=]\s*["']?[^\s"',;]{4,}/gi,
  /\b[a-z][a-z0-9+.-]*:\/\/[^\s:/@]+:[^\s@/]+@/gi,
]
const URL = /\b(?:https?|wss?|ftp):\/\/[^\s)>\]]+|\bwww\.[^\s)>\]]+/gi
const HASH = /\b(?=[0-9a-fA-F]*[a-fA-F])(?=[0-9a-fA-F]*\d)[0-9a-fA-F]{12,64}\b/g
const UUID = /\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b/g
const PATH = /(?<![\w/])(?:[A-Za-z]:\\|~?\/|\.{1,2}\/)?(?:[\w.@-]+[/\\]){2,}([\w.@-]+)/g
const INLINE_CODE = /`([^`\n]*)`/g
const MD_LINK = /!?\[([^\]]*)\]\(([^)]*)\)/g
const EMPHASIS = /(\*\*|__|\*|_|~~)(?=\S)(.+?)(?<=\S)\1/g
const HEADING = /^\s{0,3}#{1,6}\s+/gm
const QUOTE = /^\s{0,3}>\s?/gm
const LIST_MARKER = /^\s*(?:[-*+]|\d+[.)])\s+/gm
const HTML_TAG = /<\/?[A-Za-z][^>]*>/g
const STACK_LINE =
  /^\s*(?:at\s+\S+\s*\(|at\s+[\w.$<>]+:\d+|File "[^"]+", line \d+|Traceback \(most recent call last\)|\w+(?:Error|Exception):\s|panicked at|thread '.*' panicked)/
const DIFF_LINE = /^(?:@@ .* @@|\+\+\+ |--- |diff --git |index [0-9a-f]+\.\.)/
const JSONISH = /^\s*[\[{].*["'][\w-]+["']\s*:.*$|^\s*["'][\w-]+["']\s*:\s*/
const SPLIT_LINES = /\r\n|[\n\r\v\f\x1c\x1d\x1e\x85\u2028\u2029]/
const HAS_WORD = /[\p{L}\p{N}_]/u

export function redactSecrets(text: string, language: string): string {
  const replacement = phrase(language, "secret")
  let out = text
  for (const pattern of SECRET_PATTERNS) out = out.replace(pattern, () => replacement)
  return out
}

function isUnspeakableLine(line: string): boolean {
  const stripped = line.trim()
  if (!stripped) return false
  if (STACK_LINE.test(stripped) || DIFF_LINE.test(stripped) || JSONISH.test(stripped)) return true
  // Long tokens without spaces (minified code, base64, logs) are noise aloud.
  let longest = 0
  for (const token of stripped.split(/\s+/)) longest = Math.max(longest, token.length)
  if (longest > 60) return true
  let symbols = 0
  for (const character of stripped) if ("{}[]();=<>|&$\\".includes(character)) symbols++
  return stripped.length > 12 && symbols / stripped.length > 0.18
}

/** Return speakable text for one prose segment, or null to skip it. */
export function render(text: string, language: string): string | null {
  text = redactSecrets(text, language)
  const keptLines = text.split(SPLIT_LINES).filter((line) => !isUnspeakableLine(line))
  if (keptLines.length === 0) return text.trim() ? phrase(language, "details") : null
  text = keptLines.join("\n")
  text = text.replace(HTML_TAG, " ")
  text = text.replace(MD_LINK, (_match, label: string) => label || phrase(language, "link"))
  text = text.replace(URL, () => phrase(language, "link"))
  text = text.replace(UUID, "")
  text = text.replace(INLINE_CODE, (_match, code: string) => (code.length <= 32 ? code : ""))
  text = text.replace(PATH, (_match, last: string | undefined) => last ?? "")
  text = text.replace(HASH, "")
  text = text.replace(HEADING, "")
  text = text.replace(QUOTE, "")
  text = text.replace(LIST_MARKER, "")
  for (let pass = 0; pass < 2; pass++) text = text.replace(EMPHASIS, (_match, _marker, inner: string) => inner)
  text = text.replaceAll("`", "").replaceAll("|", " ")
  text = text.replace(/\s+/g, " ").trim()
  text = text.replace(/\s+([,.;:!?])/g, "$1")
  text = text.replace(/\(\s*\)|\[\s*\]/g, "").trim()
  if (!HAS_WORD.test(text)) return null
  return text
}

/** The reference pipeline's `segment_text`: markers become localised
 * phrases, prose goes through `render`. Returns null when nothing should be
 * spoken for this segment. */
export function renderSegment(segment: SpeechSegment, language: string): string | null {
  if (segment.kind === "code") return phrase(language, "code")
  if (segment.kind === "table") return phrase(language, "table")
  if (segment.kind === "list_rest") return phrase(language, "list_rest", { count: segment.count })
  return render(segment.text, language)
}
