/* SPDX-License-Identifier: MIT */
/** Incremental segmentation of a streamed LLM answer into speakable units.
 *
 * TypeScript port of the Python reference in
 * `packages/voice-host/voice_host/live/segmenter.py`. Segments end at
 * linguistic boundaries (sentence end, paragraph, list item) rather than at a
 * a fixed character count, so each synthesized unit carries a complete
 * prosodic phrase. Code fences, tables and long lists are collapsed into one
 * short marker segment each; the renderer turns markers into a spoken
 * reference to the conversation.
 *
 * Parity with the reference implementation is enforced by
 * `packages/voice-core/fixtures/speech-text-parity.json`, generated by
 * `scripts/voice/generate-speech-fixtures.py` and asserted from both sides
 * (`speech-text-parity.test.ts` here, `tests/test_text_parity.py` in
 * Voice Host).
 *
 * Faithfulness notes: Python indexes code points and strips Unicode
 * whitespace with `str.strip()`; this port uses UTF-16 indices and
 * `String.trim()`. The two agree for the five supported languages (BMP text,
 * no exotic line breaks), which is the parity fixture's input domain.
 */

export type SpeechSegmentKind = "prose" | "code" | "table" | "list_rest"

export interface SpeechSegment {
  kind: SpeechSegmentKind
  text: string
  count: number
}

export const FIRST_MIN_CHARS = 2
export const MERGE_BELOW_CHARS = 40
export const MAX_CHARS = 220
export const MAX_LIST_ITEMS = 5

const ABBREVIATIONS = new Set([
  "e.g",
  "i.e",
  "etc",
  "vs",
  "mr",
  "mrs",
  "ms",
  "dr",
  "st",
  "no",
  "fig",
  "approx",
  "cf",
  "p.ex",
  "env",
  "mme",
  "m",
  "sr",
  "sra",
  "dott",
  "sig",
  "z.b",
  "bzw",
  "usw",
  "ca",
  "nr",
])

const FENCE = /^\s{0,3}(```|~~~)/
const LIST_ITEM = /^\s*(?:[-*+]|\d+[.)])\s+\S/
const TABLE_ROW = /^\s*\|.*\|\s*$/
const CLAUSE_BREAK = /[,;:](?=\s)/g
const SENTENCE_END = /[.!?…]+["'»”)\]]*(?=\s)/g
/** Python `[\w.]+$` (letters, digits, underscore, dot) with its
 * end-of-string-or-final-newline `$` semantics. */
const WORD_BEFORE = /[\p{L}\p{N}_.]+$/u
const SINGLE_LETTER = /^\p{L}$/u

export function speechSegment(kind: SpeechSegmentKind, text = "", count = 0): SpeechSegment {
  return { kind, text, count }
}

/** Index just after the first stable sentence boundary, if any. Mirrors the
 * Python reference: decimals never end a sentence (no space after `.`) and
 * single-letter / abbreviation tokens after `.` are skipped. */
function sentenceEnd(text: string, start = 0): number | null {
  const slice = text.slice(start)
  SENTENCE_END.lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = SENTENCE_END.exec(slice))) {
    const end = start + match.index + match[0].length
    const before = slice.slice(0, match.index).replace(/\n$/, "")
    const word = WORD_BEFORE.exec(before)
    const token = (word?.[0] ?? "").toLowerCase().replace(/\.+$/, "")
    if (match[0].startsWith(".")) {
      if (ABBREVIATIONS.has(token) || (token.length === 1 && SINGLE_LETTER.test(token))) continue
    }
    return end
  }
  return null
}

export class SpeechSegmenter {
  private line = "" // current, still-growing line
  private prose = "" // completed prose not yet emitted
  private inFence = false
  private fenceMarker = ""
  private codeReported = false
  private tableReported = false
  private listItems = 0
  private emittedAny = false

  /** Whether at least one segment has been released (drives the merge floor). */
  get emitted(): boolean {
    return this.emittedAny
  }

  /** Feed one streamed delta; returns the segments it completed. */
  push(delta: string): SpeechSegment[] {
    const out: SpeechSegment[] = []
    this.line += delta
    for (;;) {
      const newline = this.line.indexOf("\n")
      if (newline < 0) break
      const line = this.line.slice(0, newline)
      this.line = this.line.slice(newline + 1)
      out.push(...this.completeLine(line))
    }
    if (!this.inFence && !this.lineMayBeBlockStart(this.line)) out.push(...this.drain(this.line))
    return out
  }

  /** Call once the stream ends; releases everything still buffered. */
  flush(): SpeechSegment[] {
    const out: SpeechSegment[] = []
    if (this.line) {
      const line = this.line
      this.line = ""
      out.push(...this.completeLine(line))
    }
    out.push(...this.closeList())
    out.push(...this.drain("", true))
    this.inFence = false
    return out
  }

  private lineMayBeBlockStart(line: string): boolean {
    const stripped = line.trimStart()
    return stripped.startsWith("`") || stripped.startsWith("~") || stripped.startsWith("|") || (stripped === "" && line !== "")
  }

  private completeLine(line: string): SpeechSegment[] {
    const out: SpeechSegment[] = []
    const fence = FENCE.exec(line)
    if (this.inFence) {
      if (fence && fence[1] === this.fenceMarker) this.inFence = false
      return out
    }
    if (fence) {
      out.push(...this.closeList())
      out.push(...this.drain("", true))
      this.inFence = true
      this.fenceMarker = fence[1]
      if (!this.codeReported) {
        this.codeReported = true
        out.push(speechSegment("code"))
      }
      return out
    }
    if (TABLE_ROW.test(line)) {
      out.push(...this.closeList())
      out.push(...this.drain("", true))
      if (!this.tableReported) {
        this.tableReported = true
        out.push(speechSegment("table"))
      }
      return out
    }
    if (LIST_ITEM.test(line)) {
      out.push(...this.drain("", true))
      this.listItems++
      if (this.listItems <= MAX_LIST_ITEMS) {
        out.push(speechSegment("prose", line.trim()))
        this.emittedAny = true
      }
      return out
    }
    out.push(...this.closeList())
    if (!line.trim()) {
      // Paragraph break: whatever prose is buffered is complete.
      out.push(...this.drain("", true))
      return out
    }
    this.prose += `${line}\n`
    out.push(...this.drain())
    return out
  }

  private closeList(): SpeechSegment[] {
    const hidden = this.listItems - MAX_LIST_ITEMS
    this.listItems = 0
    return hidden > 0 ? [speechSegment("list_rest", "", hidden)] : []
  }

  private drain(partial = "", final = false): SpeechSegment[] {
    const out: SpeechSegment[] = []
    const text = this.prose + partial
    let consumed = 0
    for (;;) {
      const remaining = text.slice(consumed)
      if (!remaining.trim()) break
      const boundary = sentenceEnd(remaining + (final ? " " : ""))
      if (boundary !== null) {
        let cut = Math.min(boundary, remaining.length)
        let candidate = remaining.slice(0, cut)
        const minimum = this.emittedAny ? MERGE_BELOW_CHARS : FIRST_MIN_CHARS
        if (candidate.trim().length < minimum && !final) {
          const following = sentenceEnd(remaining.slice(cut))
          if (following === null) break // wait for the next sentence to merge with
          cut += following
          candidate = remaining.slice(0, cut)
        }
        consumed += cut
        out.push(speechSegment("prose", candidate.trim()))
        this.emittedAny = true
        continue
      }
      if (remaining.length > MAX_CHARS) {
        const window = remaining.slice(0, MAX_CHARS)
        CLAUSE_BREAK.lastIndex = 0
        let clauseEnd = -1
        let clause: RegExpExecArray | null
        while ((clause = CLAUSE_BREAK.exec(window))) clauseEnd = clause.index + clause[0].length
        let cut = clauseEnd >= 0 ? clauseEnd : window.lastIndexOf(" ")
        if (cut <= 0) cut = MAX_CHARS
        consumed += cut
        out.push(speechSegment("prose", remaining.slice(0, cut).trim()))
        this.emittedAny = true
        continue
      }
      if (final) {
        consumed = text.length
        out.push(speechSegment("prose", remaining.trim()))
        this.emittedAny = true
      }
      break
    }
    // Only completed prose can be consumed; a partial line stays in `line`.
    const consumedFromProse = Math.min(consumed, this.prose.length)
    this.prose = this.prose.slice(consumedFromProse)
    if (consumed > consumedFromProse) {
      this.line = this.line.slice(consumed - consumedFromProse)
    }
    return out.filter((segment) => segment.text || segment.kind !== "prose")
  }
}
