/* SPDX-License-Identifier: MIT */
/**
 * UNIFIA-EOT-BENCH — End-of-Turn benchmark corpus.
 *
 * Companion to the v2 plan §19 and §25 (R4 — Common VAD and Turn
 * Detection). The corpus is a deterministic, versioned set of
 * fixtures covering the turn-detection edge cases the product must
 * handle deterministically (per the v2 plan §19):
 *
 *   short statements, questions, long sentences, pauses, hesitations,
 *   fillers, false endings, conjunction continuation, enumerations,
 *   corrections, incomplete utterances, background noise, speech over
 *   assistant audio, whisper, clipping, rapid interruption,
 *   multilingual switch.
 *
 * The corpus is shipped as JSON so it can be regenerated by tools
 * outside the TypeScript runtime (Python test runner, CI bench
 * scripts) without duplicating the dataset.
 */

import type { SpeechLanguage } from "./speech.js"

export type { SpeechLanguage } from "./speech.js"

/** A single turn-end scenario the corpus covers. */
export type EotScenario =
  | "short-statement"
  | "question"
  | "long-sentence"
  | "pause"
  | "hesitation"
  | "filler"
  | "false-ending"
  | "conjunction-continuation"
  | "enumeration"
  | "correction"
  | "incomplete-utterance"
  | "background-noise"
  | "speech-over-assistant"
  | "whisper"
  | "clipping"
  | "rapid-interruption"
  | "multilingual-switch"

/** Stable, ordered enumeration of every scenario. Used by the
 *  loader for assertions and by the bench runner for coverage
 *  reports. */
export const EOT_SCENARIOS: readonly EotScenario[] = [
  "short-statement",
  "question",
  "long-sentence",
  "pause",
  "hesitation",
  "filler",
  "false-ending",
  "conjunction-continuation",
  "enumeration",
  "correction",
  "incomplete-utterance",
  "background-noise",
  "speech-over-assistant",
  "whisper",
  "clipping",
  "rapid-interruption",
  "multilingual-switch",
] as const

/** Mandatory production languages per the v2 plan §7. */
export const EOT_LANGUAGES: readonly SpeechLanguage[] = [
  "en",
  "fr",
  "es",
  "it",
  "de",
] as const

/** A single fixture: one (language, scenario) pair plus the
 *  expected turn-detection outcome. */
export interface EotFixture {
  readonly id: string
  readonly language: SpeechLanguage
  readonly scenario: EotScenario
  /** Reference transcript (synthetic, deterministic). */
  readonly transcript: string
  /** Should the turn detector commit a turn for this fixture? */
  readonly expectedTurnComplete: boolean
  /** Optional reference audio duration in milliseconds — when set,
   *  the bench runner can measure latency against this baseline. */
  readonly expectedDurationMs?: number
  /** Optional notes describing the expected VAD/EOT behaviour. */
  readonly notes?: string
  /** Generated mono PCM and its timed benchmark annotations. */
  readonly audio: EotAudioAnnotation
}

export interface EotAudioInterval {
  readonly startMs: number
  readonly endMs: number
}

export interface EotAudioAnnotation {
  readonly path: string
  readonly spokenTranscript: string
  readonly assistantTranscript: string | null
  readonly sampleRateHz: number
  readonly durationMs: number
  readonly sha256: string
  readonly speechIntervalsMs: readonly EotAudioInterval[]
  readonly silenceIntervalsMs: readonly EotAudioInterval[]
  readonly forbiddenEotIntervalsMs: readonly EotAudioInterval[]
  readonly expectedEotMs: number | null
  readonly noiseCondition: "clean" | "background-noise" | "whisper" | "clipped"
  readonly overlapCondition: "none" | "assistant-speech"
  readonly assistantSpeechIntervalsMs: readonly EotAudioInterval[]
  readonly models: readonly {
    readonly id: string
    readonly revision: string
    readonly modelSha256: string
    readonly configSha256: string
  }[]
  readonly pythonVersion: "3.12.13"
  readonly generator: "piper-tts@1.8.0"
  readonly onnxRuntimeVersion: "1.30.0"
  readonly numpyVersion: "2.5.3"
  readonly seed: number
}

/** Top-level corpus shape, serialised to JSON. */
export interface EotBenchCorpus {
  readonly version: string
  readonly description: string
  readonly languages: readonly SpeechLanguage[]
  readonly scenarios: readonly EotScenario[]
  readonly fixtures: readonly EotFixture[]
}

/** Stable name of the on-disk corpus file shipped with the repo. */
export const EOT_BENCH_FILE = "unifia-eot-bench.json"

/** Bump when the fixture set or schema changes in a way that
 *  invalidates prior measurements. */
export const EOT_BENCH_VERSION = "2.0.0"
