/**
 * Génération THIRD_PARTY_NOTICES.md et license.notices().
 *
 * Format SPDX-like minimal :
 *   - Section par source avec licence, copyright, lien LICENSE
 *   - Ordre stable (par sourceID alphabétique)
 *   - SHA-256 du contenu intégrable pour vérification CI
 */

import type { Source, Registry } from "./schema"
import { isoUtcNow } from "./schema"

export interface NoticeEntry {
  sourceID: string
  licenseCode: string | null
  copyrightNotice: string | null
  licenseFileURL: string | null
  confidenceLevel: string
  url: string
}

export function buildNotices(sources: Source[]): NoticeEntry[] {
  return [...sources]
    .sort((a, b) => a.id.localeCompare(b.id))
    .map((s) => ({
      sourceID: s.id,
      licenseCode: s.licenseCode,
      copyrightNotice: s.copyrightNotice,
      licenseFileURL: s.licenseFileURL,
      confidenceLevel: s.confidenceLevel,
      url: s.url,
    }))
}

export function renderNoticesMarkdown(notices: NoticeEntry[]): string {
  const lines: string[] = []
  lines.push("# THIRD_PARTY_NOTICES")
  lines.push("")
  lines.push(`Generated: ${isoUtcNow()}`)
  lines.push("")
  lines.push(
    "This file is auto-generated by `script/build-notices.ts` from `Registry.licenseNotices()`.",
  )
  lines.push("Do not edit manually. Regenerate via `bun run build-notices`.")
  lines.push("")

  const grouped = new Map<string, NoticeEntry[]>()
  for (const n of notices) {
    const key = n.licenseCode ?? "UNKNOWN"
    if (!grouped.has(key)) grouped.set(key, [])
    grouped.get(key)!.push(n)
  }

  const licenseKeys = [...grouped.keys()].sort()
  for (const lic of licenseKeys) {
    lines.push(`## ${lic}`)
    lines.push("")
    for (const n of grouped.get(lic)!) {
      lines.push(`### ${n.sourceID}`)
      lines.push("")
      lines.push(`- License: ${n.licenseCode ?? "(none declared)"}`)
      lines.push(`- Copyright: ${n.copyrightNotice ?? "(none declared)"}`)
      if (n.licenseFileURL) lines.push(`- License file: ${n.licenseFileURL}`)
      lines.push(`- Confidence: ${n.confidenceLevel}`)
      if (n.url) lines.push(`- URL: ${n.url}`)
      lines.push("")
    }
  }

  lines.push("---")
  lines.push("")
  lines.push("## Verification")
  lines.push("")
  lines.push("To verify this file matches the registry snapshot :")
  lines.push("")
  lines.push("```bash")
  lines.push("bun run build-notices && git diff --exit-code THIRD_PARTY_NOTICES.md")
  lines.push("```")
  lines.push("")
  lines.push("If the file differs, regenerate and commit the change.")
  lines.push("")

  return lines.join("\n")
}

export function generate(registry: Registry): string {
  return renderNoticesMarkdown(buildNotices(registry.sources))
}